version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: clinicadmin-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinicadmin-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinicadmin-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - clinicadmin-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinicadmin-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.front
    depends_on:
      - backend
    networks:
      - clinicadmin-network

volumes:
  pgdata:

networks:
  clinicadmin-network:
    driver: bridge
